### ISSUE TITLE
Start React !

### ISSUE THREAD

**Issue by pinky0703** [pinky0703/HelloReact#1]
# React
- 손쉽게 만들 수 있는 개발 툴 

# 개발환경 설정 
- [ ] Node.js & NPM 설치 
> Node.js®는 Chrome V8 JavaScript 엔진으로 빌드된 JavaScript 런타임입니다.
Node.js는 이벤트 기반, Non 블로킹 I/O 모델을 사용해 가볍고 효율적입니다. 
Node.js의 패키지 생태계인 npm은 세계에서 가장 큰 오픈 소스 라이브러리 생태계이기도 합니다.

//잘못된 방법
this.setState(language:this.state.language);
//올바른 방법
this.setState(state => language:state.language);

### 필수 프로그램 설치
1. Github Desktop
2. Visual Studio Code 
3. Git bash
4. NVM 설치 
- [다운로드링크](https://github.com/coreybutler/nvm-windows/releases)
- [설치참고링크](https://seunghyun90.tistory.com/52)
### Slack 설치 & 가입하기
- [가입하기링크](https://www.notion.so/PC-33ec9376c85f4ffe9dd55b0fd8143bfc)
- [설치하기링크](https://slack.com/intl/ko-kr/downloads/windows)
![image](https://user-images.githubusercontent.com/29187655/148346348-2239297e-5757-4771-aaf1-d9bd51ccfb4e.png)

yarn 설치
![image](https://user-images.githubusercontent.com/29187655/148346311-d3c257a4-e7d0-480d-81bb-26bd3d68cd45.png)
![image](https://user-images.githubusercontent.com/29187655/148346399-b9df88be-1c88-442d-bb00-5f96f2f9d529.png)

# TODO
- [ ] 리액트 시작하기
[Start React](https://hello-bryan.tistory.com/97)
- [ ] Node.js 설치
[설치방법](https://hello-bryan.tistory.com/95?category=695724)
- [ ] 비동기 
- [ ] Redux에 대하여.. 
[About Redux](https://kyounghwan01.github.io/blog/React/redux/redux-basic/#%E1%84%8F%E1%85%A5%E1%86%B7%E1%84%91%E1%85%A9%E1%84%82%E1%85%A5%E1%86%AB%E1%84%90%E1%85%B3%E1%84%8B%E1%85%A6%E1%84%89%E1%85%A5-redux-%E1%84%89%E1%85%A1%E1%84%8B%E1%85%AD%E1%86%BC%E1%84%92%E1%85%A1%E1%84%80%E1%85%B5)
[About Redux2](https://pinokio0702.tistory.com/431)
- [ ] 웹 차트라이브러리 
[React Chart](https://velog.io/@eunjin/React-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EA%B7%B8%EB%9E%98%ED%94%84%EC%B0%A8%ED%8A%B8-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EB%AA%A8%EC%9D%8C)
- [ ] 최신 javascript 기술 
- [ ] 

# 참고
[링크](https://react.codepot.kr/docs/week01/doc2#create-react-app-%EC%9D%B4%EB%9E%80)
